apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: diegobran16/backend-app:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9443
          volumeMounts:
            - name: spotify-auth-volume
              mountPath: /app/spotify-auth.yaml # Ruta en el contenedor
              subPath: spotify-auth.yaml
      volumes:
        - name: spotify-auth-volume
          secret:
            secretName: spotify-auth-secret # Nombre del secreto que contiene el archivo
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 9443
      targetPort: 9443
      nodePort: 30001
  type: NodePort
